package com.phoenixkahlo.eclipse;

public enum CodableType {

	ARRAY_LIST,
	WORLD_STATE,
	BALL,
	ENTITY_ADDITION_EVENT,
	SET_VELOCITY_EVENT,
	VECTOR_2,
	PLAYER,
	BYTE_ARRAY,
	ENTITY_DELETION_EVENT,
	SPACE_BACKGROUND,
	SET_BACKGROUND_EVENT,
	SET_WALKING_ENTITY_DIRECTION_EVENT,
	SET_WALKING_ENTITY_IS_SPRINTING_EVENT,
	BASIC_PERSPECTIVE,
	SET_PERSPECTIVE_GETTER_EVENT,
	ID_PERSPECTIVE_GETTER,
	BRING_TO_TIME_EVENT,
	BASIC_SHIP_1,
	SET_RENDER_ANGLE_EVENT;
	
}
